### ISSUE TITLE
Imposible to config my MQTT Server

### ISSUE THREAD

**Issue by Eistee82** [iobroker-community-adapters/ioBroker.frigate#7]
**Describe the bug**  
There is only an MQTT Port setting. I am not abel to configure my MQTT Server. I use a dedicated MQTT Server wich is not exclusiv to iobroker and I need to connect every System to this dedicated MQTT Server!

**Comment by TA2k** [comment]
The adapter provides a own Mqtt server you can enter the iobroker ip in the frigate config
or enter your MQTT Server ip in the frigate config and passthrough all events to the iobroker ip

**Comment by Eistee82** [comment]
how to passthrough all events to the iobroker ip? I'm using mosquitto

**Comment by TA2k** [comment]
http://www.steves-internet-guide.com/mosquitto-bridge-configuration/

![](http://www.steves-internet-guide.com/wp-content/uploads/mosquitto-bridge-config-remapping-1.jpg)

instead of b2 then frigate

**Comment by Eistee82** [comment]
Sorry, that's way too complicated for me. I'd rather stick with version 0.2.8

**Comment by Eistee82** [comment]
ok no i configured the mosquitto bridge but it is not working. here the debug log:

this is my config:
```
connection iobroker-frigate
cleansession true
address iobroker:1885

topic frigate/# both 0
``` 

debug log from frigate adapter v1.2.1:
````
frigate.0 | 2024-06-15 14:17:52.635 | debug | fetchEventHistory succesfull
frigate.0 | 2024-06-15 14:17:52.633 | warn | State "frigate.0.available" has no existing object, this might lead to an error in future versions
frigate.0 | 2024-06-15 14:17:52.632 | debug | publish $SYS/98534061-eb03-4a01-a7b0-ddfb22e587f9/disconnect/clients mosquitto.iobroker-frigate
frigate.0 | 2024-06-15 14:17:52.632 | info | client disconnected mosquitto.iobroker-frigate
frigate.0 | 2024-06-15 14:17:52.632 | warn | client error: mosquitto.iobroker-frigate $SYS/ topic is reserved Error: $SYS/ topic is reserved at Aedes.defaultAuthorizePublish [as authorizePublish] (/opt/iobroker/node_modules/aedes/aedes.js:359:21) at Client.authorizePublish (/opt/iobroker/node_modules/aedes/lib/handlers/publish.js:62:15) at makeCallTwo (/opt/iobroker/node_modules/fastseries/series.js:150:3) at release (/opt/iobroker/node_modules/fastseries/series.js:138:7) at resultList (/opt/iobroker/node_modules/fastseries/series.js:125:3) at Aedes.series [as _series] (/opt/iobroker/node_modules/fastseries/series.js:45:7) at handlePublish (/opt/iobroker/node_modules/aedes/lib/handlers/publish.js:34:17) at handle (/opt/iobroker/node_modules/aedes/lib/handlers/index.js:31:7) at Parser.enqueue (/opt/iobroker/node_modules/aedes/lib/client.js:363:5) at Parser.emit (node:events:519:28)
frigate.0 | 2024-06-15 14:17:52.631 | debug | publish $SYS/98534061-eb03-4a01-a7b0-ddfb22e587f9/new/clients mosquitto.iobroker-frigate
frigate.0 | 2024-06-15 14:17:52.631 | info | Filter for message from client: mosquitto.iobroker-frigate
frigate.0 | 2024-06-15 14:17:52.630 | info | New client: mosquitto.iobroker-frigate
````
the messages repeat

**Comment by tmikulski** [comment]
@Eistee82 Have you solved your problem?

**Comment by Eistee82** [comment]
No

**Comment by GermanBluefox** [comment]
Not the usecase for this adapter
